### PR TITLE
Make annotation resolution more robust

### LINKED ISSUE #24: Resolve typealiased annotations
See https://github.com/slackhq/circuit/pull/1521

### LINKED ISSUE #32: Crash in `ClassScannerKsp` because of `@StabilityInferred` annotation cannot be resolved
KSP component merging crashes in modules which are using compose plugin because `@StabilityInferred` annotation can't be resolved for some reason.
Crashing with this exception:

```
[ksp] java.lang.IllegalArgumentException: Error type '<ERROR TYPE>' is not resolvable in the current round of processing.
	at com.squareup.kotlinpoet.ksp.KsTypesKt.requireNotErrorType(KsTypes.kt:40)
	at com.squareup.kotlinpoet.ksp.KsTypesKt.toClassName(KsTypes.kt:47)
	at com.squareup.anvil.compiler.ClassScannerKsp$findContributedClasses$2.invoke(ClassScannerKsp.kt:105)
	at com.squareup.anvil.compiler.ClassScannerKsp$findContributedClasses$2.invoke(ClassScannerKsp.kt:99)
	at kotlin.sequences.FilteringSequence$iterator$1.calcNext(Sequences.kt:171)
	at kotlin.sequences.FilteringSequence$iterator$1.hasNext(Sequences.kt:194)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.sequences.TransformingSequence$iterator$1.hasNext(Sequences.kt:214)
	at kotlin.collections.CollectionsKt__MutableCollectionsKt.addAll(MutableCollections.kt:129)
	at com.squareup.anvil.compiler.codegen.KspContributesSubcomponentHandlerSymbolProcessor.populateInitialContributions(KspContributesSubcomponentHandlerSymbolProcessor.kt:402)
	at com.squareup.anvil.compiler.codegen.KspContributesSubcomponentHandlerSymbolProcessor.computePendingEvents(KspContributesSubcomponentHandlerSymbolProcessor.kt:240)
	at com.squareup.anvil.compiler.codegen.KspContributesSubcomponentHandlerSymbolProcessor.processChecked(KspContributesSubcomponentHandlerSymbolProcessor.kt:103)
	at com.squareup.anvil.compiler.codegen.ksp.AnvilSymbolProcessor.process(AnvilSymbolProcessing.kt:31)
	at com.squareup.anvil.compiler.ClassScanningKspProcessor.processChecked(ClassScanningKspProcessor.kt:50)
	at com.squareup.anvil.compiler.codegen.ksp.AnvilSymbolProcessor.process(AnvilSymbolProcessing.kt:31)
```

### PR DESCRIPTION
**Pull request by ZacSweers**
Resolves #32 by ignoring error types when searching and copying annotations

Resolves #24 by resolving declaration through typealiases

### CODE REVIEW

**Comment by IlyaGulya** [comment]
@ZacSweers 
Is #32 supposed to be fixed already in this PR?
Because crash is still there (`ClassScannerKsp` on line 102 there's resolution of annotation with potentially error type)

**Comment by ZacSweers** [comment]
I'm adding a little more coverage in the next commit

**Comment by ZacSweers** [comment]
@IlyaGulya updated, let me know if you see any more

**Comment by IlyaGulya** [comment]
> @IlyaGulya updated, let me know if you see any more

Works fine, thanks 🙂

**Pull request merged**
